name: "Deye inverter MQTT"
description: "Relays Deye inverter data to a MQTT server"
version: "1.0.5"
slug: "deye-inverter-mqtt"
image: ghcr.io/mariusschiffer/deye-inverter-mqtt-aarch64
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  deye_logger_ip_address: ""
  deye_logger_serial_number: ""
  mqtt_host: ""
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic_prefix: ""
  deye_data_read_interval: 60
  deye_metric_groups: "string"
schema:
  deye_logger_ip_address: str
  deye_logger_serial_number: str
  mqtt_host: str
  mqtt_username: str
  mqtt_password: str
  mqtt_topic_prefix: str
  deye_data_read_interval: int
  deye_metric_groups: str
